{% set version = "2.0" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-beepr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/beepr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/beepr/beepr_{{ version }}.tar.gz
  sha256: 620e5ec93c1a0991a9c8f60868153fee1e3918b1a784f50c0e35186780c60477

build:
  number: 2
  noarch: generic

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]

  host:
    - r-base
    - r-audio
    - r-stringr >=1.0.0

  run:
    - r-base
    - r-audio
    - r-stringr >=1.0.0

test:
  commands:
    - $R -e "library('beepr')"           # [not win]
    - "\"%R%\" -e \"library('beepr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=beepr
  license: GPL-3.0-only
  summary: The main function of this package is beep(), with the purpose to make it easy to play notification sounds on whatever platform you are on. It is intended to be useful, for example, if you are running a long analysis in the background and want to know when it is ready.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler

# The original CRAN metadata for this package was:

# Package: beepr
# Type: Package
# Title: Easily Play Notification Sounds on any Platform
# Version: 1.3
# Encoding: UTF-8
# Date: 2018-06-01
# Authors@R: c( person("Rasmus", "Baath", email = "rasmus.baath@gmail.com", role = c("aut", "cre")), person("Amanda", "Dobbyn", email = "amanda.e.dobbyn@gmail.com", role = "ctb"))
# Description: The main function of this package is beep(), with the purpose to make it easy to play notification sounds on whatever platform you are on. It is intended to be useful, for example, if you are running a long analysis in the background and want to know when it is ready.
# License: GPL-3
# Imports: stringr (>= 1.0.0), audio
# RoxygenNote: 6.0.1.9000
# NeedsCompilation: no
# Packaged: 2018-06-04 10:10:29 UTC; rasmus
# Author: Rasmus Baath [aut, cre], Amanda Dobbyn [ctb]
# Maintainer: Rasmus Baath <rasmus.baath@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-06-04 10:36:35 UTC
